name: Send Repository ZIP on Push

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (change as needed)

jobs:
  zip_and_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Zip Repository
        run: |
          git archive -o repository.zip HEAD

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          # Email service configuration
          server_address: smtp.gmail.com  # Replace with your SMTP server
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Repository ZIP File
          body: Please find the attached ZIP file of the repository.
          to: navn16726@gmail.com;rharmouch@edm-cs.com  # Replace with recipient email
          from: navn16726@gmail.com  # Replace with sender email
          attachments: repository.zip

